/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginRequestDTO
 */
export interface LoginRequestDTO {
    /**
     * 
     * @type {string}
     * @memberof LoginRequestDTO
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginRequestDTO
     */
    password?: string;
}

/**
 * Check if a given object implements the LoginRequestDTO interface.
 */
export function instanceOfLoginRequestDTO(value: object): value is LoginRequestDTO {
    return true;
}

export function LoginRequestDTOFromJSON(json: any): LoginRequestDTO {
    return LoginRequestDTOFromJSONTyped(json, false);
}

export function LoginRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function LoginRequestDTOToJSON(value?: LoginRequestDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'username': value['username'],
        'password': value['password'],
    };
}

