/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskDTO } from './TaskDTO';
import {
    TaskDTOFromJSON,
    TaskDTOFromJSONTyped,
    TaskDTOToJSON,
} from './TaskDTO';

/**
 * 
 * @export
 * @interface PagedResponseTaskDTO
 */
export interface PagedResponseTaskDTO {
    /**
     * 
     * @type {Array<TaskDTO>}
     * @memberof PagedResponseTaskDTO
     */
    content?: Array<TaskDTO>;
}

/**
 * Check if a given object implements the PagedResponseTaskDTO interface.
 */
export function instanceOfPagedResponseTaskDTO(value: object): value is PagedResponseTaskDTO {
    return true;
}

export function PagedResponseTaskDTOFromJSON(json: any): PagedResponseTaskDTO {
    return PagedResponseTaskDTOFromJSONTyped(json, false);
}

export function PagedResponseTaskDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedResponseTaskDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(TaskDTOFromJSON)),
    };
}

export function PagedResponseTaskDTOToJSON(value?: PagedResponseTaskDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(TaskDTOToJSON)),
    };
}

