/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserDTO } from './UserDTO';
import {
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
} from './UserDTO';

/**
 * 
 * @export
 * @interface PagedResponseUserDTO
 */
export interface PagedResponseUserDTO {
    /**
     * 
     * @type {Array<UserDTO>}
     * @memberof PagedResponseUserDTO
     */
    content?: Array<UserDTO>;
}

/**
 * Check if a given object implements the PagedResponseUserDTO interface.
 */
export function instanceOfPagedResponseUserDTO(value: object): value is PagedResponseUserDTO {
    return true;
}

export function PagedResponseUserDTOFromJSON(json: any): PagedResponseUserDTO {
    return PagedResponseUserDTOFromJSONTyped(json, false);
}

export function PagedResponseUserDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedResponseUserDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(UserDTOFromJSON)),
    };
}

export function PagedResponseUserDTOToJSON(value?: PagedResponseUserDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(UserDTOToJSON)),
    };
}

